create TABLE IF NOT EXISTS security_logs_raw (
    log_id SERIAL PRIMARY KEY,
    event_time TIMESTAMP NOT NULL,
    username VARCHAR(100) NOT NULL,
    user_role VARCHAR(50) NOT NULL,
    account_status VARCHAR(50) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    port_number INT NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    operating_system VARCHAR(50) NOT NULL,
    browser_name VARCHAR(50) NOT NULL,
    location_city VARCHAR(100),
    location_region VARCHAR(100),
    location_country VARCHAR(100),
    event_type VARCHAR(50) NOT NULL,
    event_category VARCHAR(50) NOT NULL,
    action_taken VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_name VARCHAR(100),
    session_id VARCHAR(100) NOT NULL,
    failure_reason VARCHAR(100),
    risk_score INT NOT NULL,
    watchlist_flag BOOLEAN NOT NULL,
    notes TEXT
);