INSERT INTO security_logs_raw (event_time, username, user_role, account_status, ip_address, port_number, device_type,
                               operating_system, browser_name, location_city, location_region, location_country,
                               event_type, event_category, action_taken, status, severity, resource_type, resource_name,
                               session_id, failure_reason, risk_score, watchlist_flag, notes)
VALUES ('2026-06-01 08:00:12', 'alice_buyer', 'buyer', 'active', '192.168.1.50', 54321, 'desktop', 'Windows', 'Chrome',
        'New York', 'NY', 'USA', 'login', 'authentication', 'allow', 'success', 'low', 'user_account', 'profile',
        'sess_001', NULL, 2, FALSE, 'Normal user login'),
       ('2026-06-01 08:05:40', 'bob_vendor', 'vendor', 'active', '203.0.113.42', 443, 'server', 'Linux', 'Firefox',
        'Berlin', 'Berlin', 'Germany', 'purchase', 'transaction', 'allow', 'success', 'low', 'product_listing',
        'item_99', 'sess_002', NULL, 5, FALSE, 'Successful inventory purchase'),
       ('2026-06-01 08:12:00', 'locked_ghost', 'buyer', 'locked', '185.220.101.5', 9050, 'desktop', 'Linux', 'Tor',
        'Unknown', 'Unknown', 'Unknown', 'login', 'authentication', 'block', 'failed', 'high', 'user_account',
        'login_portal', 'sess_003', 'account_locked', 85, TRUE, 'Attempt from locked account via Tor'),
       ('2026-06-01 08:15:22', 'charlie_admin', 'admin', 'active', '10.0.0.15', 22, 'server', 'Linux', 'Chrome',
        'Austin', 'TX', 'USA', 'admin_action', 'system', 'allow', 'success', 'medium', 'admin_panel', 'config_db',
        'sess_004', NULL, 15, FALSE, 'Admin configuration update'),
       ('2026-06-01 08:20:11', 'suspect_x', 'guest', 'suspended', '198.51.100.99', 80, 'mobile', 'Android', 'Chrome',
        'Moscow', 'Moscow', 'Russia', 'login', 'authentication', 'deny', 'failed', 'critical', 'api_endpoint',
        'auth_v2', 'sess_005', 'suspicious_activity', 98, TRUE, 'Suspended account trying to access API'),
       ('2026-06-01 08:22:15', 'suspect_x', 'guest', 'suspended', '198.51.100.99', 80, 'mobile', 'Android', 'Chrome',
        'Moscow', 'Moscow', 'Russia', 'login', 'authentication', 'allow', 'success', 'critical', 'api_endpoint',
        'auth_v2', 'sess_005', NULL, 95, TRUE, 'Anomaly: Suspended account suddenly succeeded'),
       ('2026-06-01 08:30:00', 'dave_analyst', 'analyst', 'active', '10.0.0.22', 443, 'desktop', 'macOS', 'Safari',
        'Austin', 'TX', 'USA', 'file_access', 'system', 'allow', 'success', 'low', 'file_storage', 'logs_archive',
        'sess_006', NULL, 1, FALSE, 'Routine log evaluation'),
       ('2026-06-01 08:35:10', 'shared_actor', 'buyer', 'active', '45.33.32.156', 50000, 'desktop', 'Windows', 'Edge',
        'Bucharest', 'Bucharest', 'Romania', 'login', 'authentication', 'allow', 'success', 'medium', 'user_account',
        'profile', 'sess_007', NULL, 40, FALSE, 'Shared IP first login'),
       ('2026-06-01 08:36:00', 'shared_actor2', 'buyer', 'active', '45.33.32.156', 50002, 'desktop', 'Windows', 'Edge',
        'Bucharest', 'Bucharest', 'Romania', 'login', 'authentication', 'allow', 'success', 'medium', 'user_account',
        'profile', 'sess_008', NULL, 45, TRUE, 'Second user on same risky IP'),
       ('2026-06-01 08:40:05', 'eve_mod', 'moderator', 'active', '192.168.1.105', 443, 'tablet', 'iOS', 'Safari',
        'London', 'London', 'UK', 'account_update', 'user_management', 'allow', 'success', 'low', 'user_account',
        'user_99', 'sess_009', NULL, 10, FALSE, 'Moderator updating profile flags'),
       ('2026-06-01 08:42:00', 'locked_ghost', 'buyer', 'locked', '185.220.101.5', 9050, 'desktop', 'Linux', 'Tor',
        'Unknown', 'Unknown', 'Unknown', 'purchase', 'transaction', 'block', 'failed', 'high', 'transaction_record',
        'item_10', 'sess_003', 'insufficient_permissions', 90, TRUE, 'Activity on locked account'),
       ('2026-06-01 08:45:00', 'frank_guest', 'guest', 'pending', '172.16.254.1', 8080, 'kiosk', 'Linux', 'Firefox',
        'Tokyo', 'Tokyo', 'Japan', 'login', 'authentication', 'deny', 'failed', 'medium', 'user_account', 'login',
        'sess_010', 'invalid_password', 30, FALSE, 'Failed password entry');